### ISSUE TITLE
Using imports in page file

### ISSUE THREAD

**Issue by alexamy** [NakedJSX/core#3]
Can I use imports in `-page.jsx` file for JS code? Looks like all imports are thrown out and are not bundled.

Input: 
`index-page.jsx`
```jsx
import { Page } from '@nakedjsx/core/page';
import { helper } from './helpers.js';

Page.Create('en');
Page.AppendBody(<div />);
Page.AppendJs(() => {
  console.log(helper);
});
Page.Render();
```

Output:
`index.html`
```html
<!DOCTYPE html>
<html lang="en">

<head></head>

<body>
    <div></div>
    <script>
        "use strict";
        console.log(helper);
    </script>
</body>

</html>
```

**Comment by dqh-au** [comment]
Weird, looks like it's being tree shaken away incorrectly. I would have thought that would work, I'll take a look.

What is the value of the 'helper' named export in this case?

**Comment by alexamy** [comment]
I've test it with function and string (empty or not), and with build time [value](https://nakedjsx.org/documentation/#tools-definition-injection).

**Comment by dqh-au** [comment]
Ok, so I realised that you're trying to use a build-time object in the client JavaScript.

There are a few options for doing this, I'm having a play with it now. The simplest way is to move the the import to a `-client.js` file.

But I've found a couple things in this space that aren't working as I'd like them to. Although this magic construct allows you to pass a JS function from build-time:

```
import { Page } from '@nakedjsx/core/page';

const helper = () => "helper0"

Page.Create('en');
Page.AppendBody(<div />);
Page.AppendJs(helper); // works because helper is a constant function at build-time
Page.AppendJs(() => {
  console.log(helper());
});
Page.Render();
```

If you place that same function as an export in a 'helpers.mjs' file, import it into the page file, then it doesn't work. So I'll see what I can do to fix that.

And for passing arbitrary objects (not functions) to client JS I might add a new Page.Append* api soon.

**Comment by dqh-au** [comment]
try 'npx nakedjsx@test`, I just updated it with several improvements in this space

**Comment by alexamy** [comment]
Thanks for a quick reply! `0.13.0-test.3` seems isn't working, has the same result with string constant.

**Comment by dqh-au** [comment]
Can you show me the page code?

**Comment by alexamy** [comment]
`alert.js`
```javascript
export const alertMe = () => alert('Hello!');
```

`index-page.jsx`
```jsx
import { Page } from '@nakedjsx/core/page';
import { alertMe } from './alert.js';

Page.Create('en');
Page.AppendBody(<div />);
Page.AppendJs(() => alertMe());
Page.Render();
```

I had this output:
```html
<!DOCTYPE html>
<html lang="en">

<head></head>

<body>
    <div></div>
    <script>
        "use strict";
        alertMe();
    </script>
</body>

</html>
```

**Comment by dqh-au** [comment]
Ah, you need to first make the function available to client JS. Add this:

Page.AppendJs(alertMe);

**Comment by alexamy** [comment]
Yes, this way it works. Feel free to close this.

**Comment by dqh-au** [comment]
Cool. Really appreciating the bug reports btw.

**Comment by dqh-au** [comment]
Actually, this shouldn't be necessary, re-opening bug.

**Comment by dqh-au** [comment]
Actually no. Don't want page global magically bleeding over into clent js.
