### ISSUE TITLE
Feature request: PrependJs

### ISSUE THREAD

**Issue by alexamy** [NakedJSX/core#4]
Is there an option to control order when `-client.js` code is added to a script tag? I want to `AppendJs` to add code **before** appending code from dedicated `-client` file. 
There is ways to solve my problem without this feature, but I thought that this may be an useful one.

**Comment by alexamy** [comment]
Should I close this issue or you will think of adding this feature?

**Comment by dqh-au** [comment]
I think for now the approach I described is a good way to handle this situation, so yeah lets close this one.
